//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LPS
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class Car
    {
        public Car()
        {
            this.CarItems = new HashSet<CarItem>();
        }
    
        public int CarID { get; set; }
        public int CarCatID { get; set; }
        public string Model { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string Engine { get; set; }
        public string Body { get; set; }
        public string EngVol { get; set; }
        public string EngNo { get; set; }
    
        public virtual CarCategory CarCategory { get; set; }
        public virtual ICollection<CarItem> CarItems { get; set; }
    }
}
