//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LPS
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class CarCategory
    {
        public CarCategory()
        {
            this.Cars = new HashSet<Car>();
            this.ProductOwnerReferences = new HashSet<ProductOwnerReference>();
        }
    
        public int CatID { get; set; }
        public Nullable<int> CatParentID { get; set; }
        public string CatName { get; set; }
        public int CatLevel { get; set; }
    
        public virtual ICollection<Car> Cars { get; set; }
        public virtual ICollection<ProductOwnerReference> ProductOwnerReferences { get; set; }
    }
}
