//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LPS
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class CarItem
    {
        public int CarID { get; set; }
        public int ProductCatID { get; set; }
        public string ProductID { get; set; }
        public int ItemID { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Product Product { get; set; }
    }
}
