//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LPS
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class ProductOwnerReference
    {
        public string RefProductID { get; set; }
        public string ProductID { get; set; }
        public Nullable<int> CatID { get; set; }
    
        public virtual CarCategory CarCategory { get; set; }
        public virtual Product Product { get; set; }
    }
}
