//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LPS
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class ProductCategory
    {
        public ProductCategory()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int ProductCatID { get; set; }
        public string ProductCatName { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
