//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LPS
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class Product
    {
        public Product()
        {
            this.CarItems = new HashSet<CarItem>();
            this.ProductOwnerReferences = new HashSet<ProductOwnerReference>();
        }
    
        public string ProductID { get; set; }
        public int ProductCatID { get; set; }
        public string Image { get; set; }
        public string ProductName { get; set; }
        public string Specification { get; set; }
        public bool Avtive { get; set; }
    
        public virtual ICollection<CarItem> CarItems { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ICollection<ProductOwnerReference> ProductOwnerReferences { get; set; }
    }
}
